### ISSUE TITLE
Why doesn't it support 2-bit? 

### ISSUE THREAD

**Issue by foxspy** [VectorDB-NTU/Extended-RaBitQ#2]
I noticed that 2-bit support is not included in the code. Is there any specific reason for this?

**Comment by gaoj0017** [comment]
2-bit is supported by the `fast_quantize` function, i.e., you can use the function to produce a sequence of 2-bit quantization codes and store them in a sequence of uint8 byte array. This would be enough for testing its accuracy. The implementation regarding its compact storage and efficient computation has not been included in this repo because we thought 2-bit was insufficient to produce high recall without reranking. But in general, they can be achieved in very similar ways of other settings, i.e., 2-bit = 1-bit + 1-bit. We have plans to provide a more detailed document for the implementation of RaBitQ and its extension, but it may take some time.
